/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_zeewane_jni_JavaNative */

#ifndef _Included_com_github_zeewane_jni_JavaNative
#define _Included_com_github_zeewane_jni_JavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zeewane_jni_JavaNative
 * Method:    helloJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_zeewane_jni_JavaNative_helloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
